-- title data
INSERT INTO title (name) VALUES('Restaurant Manager');
INSERT INTO title (name) VALUES('Paramedic');
INSERT INTO title (name) VALUES('Chef Manager');
INSERT INTO title (name) VALUES('Food Technologist');
INSERT INTO title (name) VALUES('Loan Officer');
INSERT INTO title (name) VALUES('Lecturer');
INSERT INTO title (name) VALUES('Chef Manager');
INSERT INTO title (name) VALUES('Staffing Consultant');
INSERT INTO title (name) VALUES('Doctor');
INSERT INTO title (name) VALUES('Retail Trainee');

-- city data
INSERT INTO city (name) VALUES('Fort Lauderdale');
INSERT INTO city (name) VALUES('Wien');
INSERT INTO city (name) VALUES('Toledo');
INSERT INTO city (name) VALUES('Nashville');
INSERT INTO city (name) VALUES('Kansas City');
INSERT INTO city (name) VALUES('Glendale');
INSERT INTO city (name) VALUES('San Diego');
INSERT INTO city (name) VALUES('Saint Paul');
INSERT INTO city (name) VALUES('Venice');
INSERT INTO city (name) VALUES('Fremont');
INSERT INTO city (name) VALUES('Henderson');
INSERT INTO city (name) VALUES('Fayetteville');
INSERT INTO city (name) VALUES('Berlin');
INSERT INTO city (name) VALUES('Phoenix');
INSERT INTO city (name) VALUES('Washington');
INSERT INTO city (name) VALUES('Dallas');
INSERT INTO city (name) VALUES('New York');
INSERT INTO city (name) VALUES('Berlin');
INSERT INTO city (name) VALUES('Los Angeles');
INSERT INTO city (name) VALUES('Jacksonville');

--states data
INSERT INTO states (name) VALUES('Nebraska');
INSERT INTO states (name) VALUES('Kentucky');
INSERT INTO states (name) VALUES('Hawaii');
INSERT INTO states (name) VALUES('Georgia');
INSERT INTO states (name) VALUES('South Dakota');
INSERT INTO states (name) VALUES('Kansas');
INSERT INTO states (name) VALUES('Alabama');
INSERT INTO states (name) VALUES('Florida');
INSERT INTO states (name) VALUES('Nebraska');
INSERT INTO states (name) VALUES('Kansas');


-- customer data
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Leilani','Walter','Caldwell   Grove',144,16,5,'1-408-225-0501','Leilani_Walter8587@nickia.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Violet','Dale','Cliff  Rue',357,7,3,'5-515-878-3051','Violet_Dale3584@cispeto.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Crystal','Vollans','Addison  Way',35,15,2,'6-335-541-8665','Crystal_Vollans4566@nanoff.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Josh','Hilton','Belgrave  Route',219,13,8,'5-304-145-7605','Josh_Hilton5695@sveldo.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Wade','Larkin','Church Tunnel',148,15,5,'3-748-212-8715','Wade_Larkin870@joiniaa.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Doug','Flett','Aylward   Avenue',499,11,1,'8-687-055-1311','Doug_Flett9364@bretoux.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Marjorie','Lomax','Elba  Crossroad',205,7,9,'8-704-662-4772','Marjorie_Lomax1626@gmail.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Tony','Fleming','Cloth  Tunnel',246,14,9,'4-041-084-7455','Tony_Fleming2016@nanoff.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Liam','Jefferson','Andrews  Boulevard',470,9,7,'4-376-863-8548','Liam_Jefferson6783@yahoo.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Abdul','Walsh','King Edward  Way',364,17,7,'2-168-132-6584','Abdul_Walsh2627@gembat.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Mandy','Matthews','Charnwood   Vale',123,2,10,'8-064-151-3061','Mandy_Matthews5939@extex.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Barry','Fall','Rail Pass',153,3,2,'8-533-740-7844','Barry_Fall7504@bauros.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Matt','London','Monroe Alley',413,3,4,'4-136-164-4538','Matt_London9213@brety.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Chris','Holt','Ernest  Boulevard',24,2,6,'1-267-271-0354','Chris_Holt7@qater.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Havana','Shelton','Fawn Way',439,10,4,'3-047-034-6267','Havana_Shelton404@hourpy.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Carter','Cowan','Caslon   Drive',413,7,4,'1-648-740-2361','Carter_Cowan5979@sveldo.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Sebastian','Driscoll','Canon Tunnel',212,14,4,'0-868-004-3850','Sebastian_Driscoll1686@extex.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Leroy','Price','Eldon  Vale',446,10,5,'8-053-666-3763','Leroy_Price6594@fuliss.net');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Liam','Moran','Boleyn  Crossroad',258,12,9,'3-013-148-0014','Liam_Moran2032@ovock.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Jane','Kirby','Lexington Boulevard',158,17,10,'0-854-803-2823','Jane_Kirby9088@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Davina','Palmer','Canon Hill',88,14,4,'6-574-000-6341','Davina_Palmer7225@zorer.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Javier','Ebbs','Ben   Vale',231,13,8,'1-712-348-5461','Javier_Ebbs1622@nickia.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Daron','Evans','Blore  Lane',494,8,7,'4-611-617-0036','Daron_Evans451@womeona.net');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Abdul','Bailey','Wakley   Rue',263,3,1,'8-705-187-6724','Abdul_Bailey2730@twace.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Cecilia','Williams','Ernest  Rue',170,3,6,'3-231-174-0814','Cecilia_Williams2369@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Eduardo','Carpenter','Fawn Avenue',140,19,4,'2-126-385-6001','Eduardo_Carpenter110@cispeto.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Chris','Olivier','Colombo   Alley',32,7,7,'8-000-501-7410','Chris_Olivier1711@liret.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('David','Logan','Duthie   Pass',482,18,4,'7-122-004-4131','David_Logan6118@deavo.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Maxwell','Kelly','Thrale   Crossroad',404,10,9,'5-717-233-4020','Maxwell_Kelly4417@bretoux.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Rocco','Thorne','Cecilia  Avenue',22,15,4,'2-675-488-8581','Rocco_Thorne4065@elnee.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Johnny','Burge','Chalcot  Walk',351,2,1,'0-011-303-4826','Johnny_Burge7399@cispeto.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Aeris','Palmer','Geffrye   Pass',200,10,5,'4-380-774-5363','Aeris_Palmer6766@ubusive.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Evelynn','Maxwell','West Vale',415,11,5,'6-535-881-7002','Evelynn_Maxwell5736@grannar.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Cynthia','Shaw','Queensberry  Avenue',116,18,10,'4-530-104-5855','Cynthia_Shaw9575@yahoo.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Erick','Lloyd','Chapel  Drive',443,6,8,'2-500-758-4255','Erick_Lloyd6510@grannar.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Ronald','Cobb','Victorian  Pass',466,16,4,'1-465-477-5643','Ronald_Cobb5938@tonsy.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Eduardo','Brown','Boleyn  Route',220,10,1,'5-882-457-5628','Eduardo_Brown5118@joiniaa.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Elijah','Swan','Andsell    Tunnel',414,3,10,'4-020-380-5524','Elijah_Swan3017@twipet.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Shannon','Stewart','Blackwall  Road',83,2,1,'0-230-606-0415','Shannon_Stewart3619@sveldo.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Hayden','Sherwood','Thomas More   Vale',313,15,10,'1-841-146-4125','Hayden_Sherwood365@qater.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Erick','Reid','Elia   Hill',459,8,6,'1-178-135-0084','Erick_Reid3424@dionrab.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Paige','Kelly','Thomas Doyle   Rue',276,1,6,'2-782-250-7246','Paige_Kelly3745@corti.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Sara','Norton','Apostle  Drive',50,2,5,'1-316-753-8083','Sara_Norton3475@ovock.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Ada','Strong','Geary   Lane',382,12,3,'7-378-585-3564','Ada_Strong9194@famism.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Martha','Mitchell','Durham Avenue',27,13,10,'1-530-403-5503','Martha_Mitchell5143@twipet.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Lynn','Lewis','Longleigh   Street',341,16,6,'4-283-867-1846','Lynn_Lewis9482@twipet.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Jenna','Whitehouse','Aberavon  Road',423,6,8,'8-613-674-4823','Jenna_Whitehouse8370@ubusive.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Domenic','Bright','Elba  Way',193,12,6,'6-555-862-7717','Domenic_Bright5281@zorer.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Jacqueline','Clark','Heritage Vale',423,8,6,'0-131-883-0334','Jacqueline_Clark6996@tonsy.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Lucy','Knight','Howard Walk',66,4,8,'1-042-417-5544','Lucy_Knight2029@bungar.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Paige','Emmott','Angela   Road',384,20,8,'3-637-623-2136','Paige_Emmott1743@guentu.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Maddison','Salt','Fairbairn  Avenue',418,10,5,'6-884-266-1363','Maddison_Salt2247@infotech44.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Ada','Truscott','Beechen  Walk',413,10,4,'3-170-052-4558','Ada_Truscott4749@bretoux.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Violet','Yang','King Edward  Route',304,13,1,'7-538-826-5260','Violet_Yang289@sveldo.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Angelina','Steer','Vintners  Street',20,10,8,'6-136-584-6131','Angelina_Steer8063@liret.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Cassidy','Gaynor','Carltoun   Vale',179,11,9,'2-784-121-3715','Cassidy_Gaynor1666@gmail.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Nick','Foxley','Camberwell  Tunnel',141,6,10,'1-272-772-5306','Nick_Foxley9623@bulaffy.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Mark','Payne','Underwood  Grove',347,8,4,'2-155-740-4770','Mark_Payne2264@guentu.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Eden','Ross','Fieldstone Boulevard',263,18,8,'4-081-451-3875','Eden_Ross9385@mafthy.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Roger','Rainford','Hammersmith  Road',126,4,1,'4-256-026-3011','Roger_Rainford4664@vetan.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Charlize','Oakley','Udall   Route',431,18,2,'8-042-224-8522','Charlize_Oakley7042@muall.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Manuel','Cann','Vintners  Grove',211,9,1,'7-534-808-3153','Manuel_Cann3036@bungar.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Chester','Farrow','Queen Caroline   Pass',487,6,4,'3-786-872-4883','Chester_Farrow4400@deons.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Lucas','Nicolas','Bempton   Boulevard',97,11,7,'4-573-636-1064','Lucas_Nicolas1815@muall.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Harriet','Malone','Linda   Road',115,14,10,'1-687-736-0537','Harriet_Malone7330@naiker.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Barry','Benson','Bury  Tunnel',206,12,3,'8-182-375-4028','Barry_Benson8504@nimogy.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Iris','Wilson','Arundel   Crossroad',38,20,2,'3-254-735-4367','Iris_Wilson943@iatim.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Jamie','Brock','Bacon  Route',286,3,5,'4-177-052-0733','Jamie_Brock6256@atink.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Daniel','Hill','Cecilia  Hill',179,1,1,'6-416-004-8844','Daniel_Hill8053@muall.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Macy','Harvey','Queen Walk',401,7,5,'4-344-465-5771','Macy_Harvey1355@kideod.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Naomi','Bristow','Bell    Road',274,17,1,'8-877-466-4275','Naomi_Bristow7031@mafthy.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Rachael','Wilde','Arthur  Way',206,18,4,'1-526-105-1362','Rachael_Wilde4799@acrit.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Emely','Davies','Blendon    Drive',485,17,2,'4-053-744-0731','Emely_Davies9543@brety.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Sonya','Marshall','Camley   Boulevard',306,3,4,'7-022-255-0553','Sonya_Marshall276@gembat.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Martin','Sherry','Belmont Park Boulevard',275,3,2,'5-214-572-0453','Martin_Sherry7070@hourpy.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Doug','Cox','Westcott  Way',468,17,10,'1-768-415-8880','Doug_Cox108@twace.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Joseph','Logan','Marina  Way',362,8,9,'1-002-376-2065','Joseph_Logan2965@nanoff.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Bob','Woods','Elba  Alley',353,14,3,'5-626-641-1481','Bob_Woods4782@deons.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Emerald','Cowan','Bacon  Vale',164,19,7,'7-246-871-6040','Emerald_Cowan6798@nimogy.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Erin','Irwin','Fawn Rue',150,10,2,'4-637-036-7883','Erin_Irwin7494@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Tyson','Thatcher','Wake  Pass',369,20,5,'3-417-343-7830','Tyson_Thatcher4618@womeona.net');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Aiden','Bell','Monroe Lane',230,10,10,'0-458-178-8585','Aiden_Bell4736@nimogy.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Brad','Pitt','Maple Rue',420,7,10,'0-432-038-7072','Brad_Pitt5347@kideod.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Anthony','Nash','Apsley    Tunnel',323,11,9,'3-448-722-7725','Anthony_Nash1080@infotech44.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Eileen','Squire','Cobden  Alley',261,20,2,'5-128-272-5131','Eileen_Squire8453@sveldo.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Miley','Eyres','Tilloch   Street',36,15,10,'1-553-418-2211','Miley_Eyres5211@brety.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Johnny','Butler','Catherine  Way',232,19,2,'6-732-738-3374','Johnny_Butler2669@tonsy.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('George','Kelly','Cleveland  Pass',294,7,4,'8-102-376-6255','George_Kelly8010@bauros.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Joseph','Tennant','Yorkshire  Way',392,2,9,'7-262-436-5477','Joseph_Tennant5872@typill.biz');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Danielle','Cox','Bective  Grove',270,3,8,'0-274-377-3307','Danielle_Cox2281@womeona.net');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Daniel','Warner','Bolingbroke  Crossroad',224,20,2,'6-661-861-7212','Daniel_Warner9585@atink.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Gabriel','Wilcox','Bicknell  Alley',289,20,2,'1-603-266-8750','Gabriel_Wilcox1623@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Marjorie','Huggins','Virginia Avenue',86,14,6,'1-852-327-5267','Marjorie_Huggins6@infotech44.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Kieth','Newman','South Rue',468,9,10,'3-517-534-6453','Kieth_Newman3054@muall.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Denis','Nelson','Eaglet  Lane',249,17,5,'5-711-574-4372','Denis_Nelson2491@vetan.org');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Denny','York','Wager   Walk',423,8,9,'6-146-241-1663','Denny_York6000@cispeto.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Olivia','Archer','Earl Rise Drive',277,20,3,'1-610-024-0505','Olivia_Archer4367@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Julius','Holmes','Vintners  Tunnel',199,8,3,'5-075-085-4772','Julius_Holmes4068@gompie.com');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Domenic','Stevenson','Bedford  Boulevard',78,14,1,'1-571-880-1161','Domenic_Stevenson6000@infotech44.tech');
INSERT INTO customers (firstname, lastname, street, str_number, city_id, state_id, phone, email) VALUES('Danny','Gray','Coalecroft  Lane',154,18,7,'7-230-022-4782','Danny_Gray7193@eirey.tech');

-- employee data
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Isla','Lee','Cleaver Avenue',64,12,3,'8-206-635-6034','Isla_Lee1767@nanoff.biz',4);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Leah','Fowler','Blenkarne  Crossroad',367,4,8,'0-785-728-1288','Leah_Fowler33@nanoff.biz',6);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Chester','Warden','Elia   Way',302,13,5,'4-706-304-2270','Chester_Warden1490@twace.org',2);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Daphne','Simpson','Chalcot  Crossroad',474,4,5,'2-116-754-7041','Daphne_Simpson6419@supunk.biz',1);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Doris','Lane','Cephas  Way',1,14,1,'8-031-353-2762','Doris_Lane9953@iatim.tech',9);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Mason','Middleton','Thomas Doyle   Pass',219,15,6,'0-466-534-0317','Mason_Middleton1336@jiman.org',2);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Benny','Marshall','Ben   Grove',427,16,5,'3-336-514-6223','Benny_Marshall3780@extex.org',10);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Benjamin','Benson','Catherine  Pass',369,8,2,'1-453-365-7086','Benjamin_Benson5897@atink.com',4);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Norah','Dale','Vincent  Hill',296,18,6,'7-713-058-3100','Norah_Dale2064@tonsy.org',10);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Valerie','Egerton','Chesterfield  Vale',226,5,5,'5-371-212-4162','Valerie_Egerton6644@deavo.com',7);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Julia','Lane','Canal  Lane',312,16,8,'4-813-543-8442','Julia_Lane3191@jiman.org',8);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Ramon','Hunt','Buttonwood Alley',334,18,3,'8-424-870-1456','Ramon_Hunt8829@guentu.biz',9);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Priscilla','Norton','Calverley  Road',126,7,8,'3-335-365-1407','Priscilla_Norton2249@infotech44.tech',7);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Livia','Wellington','Carlton  Crossroad',133,18,7,'5-376-021-3558','Livia_Wellington1727@nanoff.biz',9);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Noemi','Drew','Camdale  Hill',182,2,6,'0-572-740-3308','Noemi_Drew6928@sheye.org',1);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Boris','Snell','Blackwall  Road',97,9,3,'2-742-021-4645','Boris_Snell495@acrit.org',2);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Anne','Ebbs','Erindale Tunnel',117,6,10,'2-400-566-2271','Anne_Ebbs8149@joiniaa.com',1);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Logan','Murphy','West Tunnel',411,7,4,'0-664-887-3818','Logan_Murphy3280@womeona.net',1);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Davina','Connor','Gautrey  Crossroad',245,5,8,'8-466-772-4835','Davina_Connor8970@gmail.com',4);
INSERT INTO employee (firstname, lastname, street, str_number, city_id, state_id, phone, email, title_id) VALUES('Moira','Kennedy','Commercial  Route',467,20,10,'7-057-340-6871','Moira_Kennedy3938@naiker.biz',2);
