insert into categories (category_name) values ('processor'), ('video card')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 3600', '1', '11', '22')
insert into products (product_name, category_id, stock, price) values ('Ryzen 3 4100', '1', '12', '86')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 5600X', '1', '2', '38')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 5600G', '1', '0', '39')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5800X', '1', '1', '58')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5800X3D', '1', '12', '72')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5700X', '1', '19', '73')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 5500U', '1', '15', '81')
insert into products (product_name, category_id, stock, price) values ('Ryzen 9 5950X', '1', '18', '33')
insert into products (product_name, category_id, stock, price) values ('Core i9-12900KS', '1', '5', '3')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 PRO 4650G', '1', '16', '25')
insert into products (product_name, category_id, stock, price) values ('FX-6300', '1', '6', '39')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5700G', '1', '8', '19')
insert into products (product_name, category_id, stock, price) values ('A8-7680', '1', '5', '74')
insert into products (product_name, category_id, stock, price) values ('Core i5-10400F', '1', '8', '91')
insert into products (product_name, category_id, stock, price) values ('FX-8350', '1', '17', '95')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 3700X', '1', '9', '95')
insert into products (product_name, category_id, stock, price) values ('Core 2 Duo E8400', '1', '9', '49')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 2600', '1', '19', '87')
insert into products (product_name, category_id, stock, price) values ('Core i5-3470', '1', '16', '42')
insert into products (product_name, category_id, stock, price) values ('Ryzen 9 5900X', '1', '7', '17')
insert into products (product_name, category_id, stock, price) values ('Core i9-12900K', '1', '1', '58')
insert into products (product_name, category_id, stock, price) values ('Ryzen 3 3200G', '1', '7', '1')
insert into products (product_name, category_id, stock, price) values ('Core i7-3770', '1', '4', '12')
insert into products (product_name, category_id, stock, price) values ('Core i7-12700F', '1', '3', '43')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5800H', '1', '14', '94')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 4600G', '1', '9', '50')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 5500', '1', '16', '95')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 5800G', '1', '13', '50')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 6800U', '1', '14', '14')
insert into products (product_name, category_id, stock, price) values ('Core i7-2600', '1', '15', '49')
insert into products (product_name, category_id, stock, price) values ('Core i5-12400F', '1', '11', '25')
insert into products (product_name, category_id, stock, price) values ('Core i3-10100', '1', '10', '46')
insert into products (product_name, category_id, stock, price) values ('Core i7-12700K', '1', '11', '2')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 3500X', '1', '18', '30')
insert into products (product_name, category_id, stock, price) values ('Core i5-650', '1', '19', '66')
insert into products (product_name, category_id, stock, price) values ('Athlon 3000G', '1', '0', '5')
insert into products (product_name, category_id, stock, price) values ('Core i7-11800H', '1', '4', '78')
insert into products (product_name, category_id, stock, price) values ('Core i5-12400', '1', '17', '9')
insert into products (product_name, category_id, stock, price) values ('Ryzen 5 1600', '1', '14', '54')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 6800H', '1', '7', '89')
insert into products (product_name, category_id, stock, price) values ('Ryzen 3 2200G', '1', '2', '39')
insert into products (product_name, category_id, stock, price) values ('Ryzen 7 2700X', '1', '4', '46')
insert into products (product_name, category_id, stock, price) values ('Core i7-1260P', '1', '8', '87')
insert into products (product_name, category_id, stock, price) values ('FX-8320', '1', '15', '33')
insert into products (product_name, category_id, stock, price) values ('Core i5-2400', '1', '2', '47')
insert into products (product_name, category_id, stock, price) values ('Ryzen 3 3100', '1', '11', '45')
insert into products (product_name, category_id, stock, price) values ('Core 2 Quad Q6600 (95W)', '1', '6', '98')
insert into products (product_name, category_id, stock, price) values ('Athlon II X2 250', '1', '4', '44')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3090 Ti', '2', '2', '20')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3060', '2', '15', '71')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3060 Ti', '2', '0', '13')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3080', '2', '9', '64')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3050 8 GB', '2', '7', '89')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3070', '2', '0', '61')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6600 XT', '2', '15', '140')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3070 Ti', '2', '2', '41')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3090', '2', '14', '120')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2060', '2', '1', '2')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6600', '2', '5', '119')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6700 XT', '2', '16', '122')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 3080 Ti', '2', '13', '126')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1050 Ti', '2', '19', '93')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 970', '2', '18', '40')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1060 6 GB', '2', '9', '87')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1080 Ti', '2', '11', '132')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1070', '2', '18', '34')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1650', '2', '3', '81')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 960', '2', '6', '118')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6900 XT', '2', '18', '101')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6500 XT', '2', '1', '133')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1080', '2', '2', '14')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 580', '2', '7', '99')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 570', '2', '7', '47')
insert into products (product_name, category_id, stock, price) values ('GeForce GT 1030', '2', '1', '128')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1660 Ti', '2', '12', '71')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1660 SUPER', '2', '14', '68')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 550', '2', '15', '100')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 750 Ti', '2', '16', '58')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2080 Ti', '2', '13', '115')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1050', '2', '0', '126')
insert into products (product_name, category_id, stock, price) values ('GeForce 210', '2', '17', '107')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 6800 XT', '2', '8', '146')
insert into products (product_name, category_id, stock, price) values ('GeForce GT 730', '2', '14', '33')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1650 SUPER', '2', '13', '47')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 4090', '2', '5', '109')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 550 Ti', '2', '14', '90')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 1660', '2', '10', '77')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2070', '2', '17', '36')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2070 SUPER', '2', '3', '43')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 950', '2', '17', '52')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 980 Ti', '2', '19', '62')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 4070', '2', '10', '66')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 760', '2', '5', '18')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2060 SUPER', '2', '11', '38')
insert into products (product_name, category_id, stock, price) values ('GeForce RTX 2080', '2', '10', '139')
insert into products (product_name, category_id, stock, price) values ('Radeon RX 5700 XT', '2', '0', '56')
insert into products (product_name, category_id, stock, price) values ('GeForce GTX 980', '2', '18', '3')
insert into city (name) values ('Budapest')
insert into city (name) values ('Debrecen')
insert into city (name) values ('Szeged')
insert into city (name) values ('Miskolc')
insert into city (name) values ('Pécs')
insert into city (name) values ('Győr')
insert into city (name) values ('Nyíregyháza')
insert into city (name) values ('Kecskemét')
insert into city (name) values ('Székesfehérvár')
insert into city (name) values ('Szombathely')
insert into city (name) values ('Szolnok')
insert into city (name) values ('Érd')
insert into city (name) values ('Tatabánya')
insert into city (name) values ('Sopron')
insert into city (name) values ('Kaposvár')
insert into city (name) values ('Veszprém')
insert into city (name) values ('Békéscsaba')
insert into city (name) values ('Zalaegerszeg')
insert into city (name) values ('Eger')
insert into city (name) values ('Nagykanizsa')
insert into city (name) values ('Dunaújváros')
insert into city (name) values ('Dunakeszi')
insert into city (name) values ('Hódmezővásárhely')
insert into city (name) values ('Szigetszentmiklós')
insert into city (name) values ('Vác')
insert into city (name) values ('Cegléd')
insert into city (name) values ('Baja')
insert into city (name) values ('Salgótarján')
insert into city (name) values ('Mosonmagyaróvár')
insert into city (name) values ('Ózd')
insert into city (name) values ('Gödöllő')
insert into city (name) values ('Szekszárd')
insert into city (name) values ('Hajdúböszörmény')
insert into city (name) values ('Pápa')
insert into city (name) values ('Gyöngyös')
insert into city (name) values ('Gyula')
insert into city (name) values ('Kiskunfélegyháza')
insert into city (name) values ('Budaörs')
insert into city (name) values ('Esztergom')
insert into city (name) values ('Ajka')
insert into city (name) values ('Orosháza')
insert into city (name) values ('Jászberény')
insert into city (name) values ('Szentes')
insert into city (name) values ('Kiskunhalas')
insert into city (name) values ('Szentendre')
insert into city (name) values ('Kazincbarcika')
insert into city (name) values ('Siófok')
insert into city (name) values ('Hajdúszoboszló')
insert into city (name) values ('Gyál')
insert into city (name) values ('Nagykőrös')
insert into city (name) values ('Tata')
insert into city (name) values ('Komló')
insert into city (name) values ('Makó')
insert into city (name) values ('Dunaharaszti')
insert into city (name) values ('Vecsés')
insert into city (name) values ('Hatvan')
insert into city (name) values ('Törökszentmiklós')
insert into city (name) values ('Karcag')
insert into city (name) values ('Fót')
insert into city (name) values ('Várpalota')
insert into city (name) values ('Keszthely')
insert into city (name) values ('Komárom')
insert into city (name) values ('Paks')
insert into city (name) values ('Veresegyház')
insert into city (name) values ('Békés')
insert into city (name) values ('Gyömrő')
insert into city (name) values ('Százhalombatta')
insert into city (name) values ('Göd')
insert into city (name) values ('Oroszlány')
insert into city (name) values ('Monor')
insert into city (name) values ('Dombóvár')
insert into city (name) values ('Szigethalom')
insert into city (name) values ('Pomáz')
insert into city (name) values ('Balmazújváros')
insert into city (name) values ('Mohács')
insert into city (name) values ('Dabas')
insert into city (name) values ('Hajdúnánás')
insert into city (name) values ('Mátészalka')
insert into city (name) values ('Mezőkövesd')
insert into city (name) values ('Mezőtúr')
insert into city (name) values ('Kisvárda')
insert into city (name) values ('Csongrád')
insert into city (name) values ('Pécel')
insert into city (name) values ('Szarvas')
insert into city (name) values ('Kalocsa')
insert into city (name) values ('Tiszaújváros')
insert into city (name) values ('Tapolca')
insert into city (name) values ('Sárvár')
insert into city (name) values ('Balassagyarmat')
insert into city (name) values ('Berettyóújfalu')
insert into city (name) values ('Abony')
insert into city (name) values ('Budakeszi')
insert into city (name) values ('Püspökladány')
insert into city (name) values ('Pilisvörösvár')
insert into city (name) values ('Sátoraljaújhely')
insert into city (name) values ('Mór')
insert into city (name) values ('Biatorbágy')
insert into city (name) values ('Kiskőrös')
insert into city (name) values ('Törökbálint')
insert into city (name) values ('Bonyhád')
insert into city (name) values ('Hajdúsámson')
insert into city (name) values ('Balatonfüred')
insert into city (name) values ('Gyomaendrőd')
insert into city (name) values ('Újfehértó')
insert into city (name) values ('Hajdúhadház')
insert into city (name) values ('Albertirsa')
insert into city (name) values ('Tiszavasvári')
insert into city (name) values ('Maglód')
insert into city (name) values ('Nagykáta')
insert into city (name) values ('Kerepestarcsa')
insert into city (name) values ('Tiszakécske')
insert into city (name) values ('Bicske')
insert into city (name) values ('Üllő')
insert into city (name) values ('Sárbogárd')
insert into city (name) values ('Dorog')
insert into city (name) values ('Nyírbátor')
insert into city (name) values ('Bátonyterenye')
insert into city (name) values ('Kőszeg')
insert into city (name) values ('Sárospatak')
insert into city (name) values ('Sajószentpéter')
insert into city (name) values ('Pilis')
insert into city (name) values ('Isaszeg')
insert into city (name) values ('Lajosmizse')
insert into city (name) values ('Körmend')
insert into city (name) values ('Gárdony')
insert into city (name) values ('Marcali')
insert into city (name) values ('Tolna')
insert into city (name) values ('Kiskunmajsa')
insert into city (name) values ('Budakalász')
insert into city (name) values ('Kisújszállás')
insert into city (name) values ('Tiszafüred')
insert into city (name) values ('Tiszaföldvár')
insert into city (name) values ('Celldömölk')
insert into city (name) values ('Ráckeve')
insert into city (name) values ('Halásztelek')
insert into city (name) values ('Diósd')
insert into city (name) values ('Barcs')
insert into city (name) values ('Szigetvár')
insert into city (name) values ('Solymár')
insert into city (name) values ('Kapuvár')
insert into city (name) values ('Heves')
insert into city (name) values ('Csorna')
insert into city (name) values ('Nagyatád')
insert into city (name) values ('Tököl')
insert into city (name) values ('Mezőberény')
insert into city (name) values ('Csömör')
insert into city (name) values ('Sarkad')
insert into city (name) values ('Tárnok')
insert into city (name) values ('Edelény')
insert into city (name) values ('Ócsa')
insert into city (name) values ('Nagykálló')
insert into city (name) values ('Pásztó')
insert into city (name) values ('Siklós')
insert into city (name) values ('Kiskunlacháza')
insert into city (name) values ('Szentgotthárd')
insert into city (name) values ('Szeghalom')
insert into city (name) values ('Hajdúdorog')
insert into city (name) values ('Szerencs')
insert into city (name) values ('Balatonalmádi')
insert into city (name) values ('Nádudvar')
insert into city (name) values ('Vásárosnamény')
insert into city (name) values ('Dunaföldvár')
insert into city (name) values ('Túrkeve')
insert into city (name) values ('Kecel')
insert into city (name) values ('Derecske')
insert into city (name) values ('Piliscsaba')
insert into city (name) values ('Jánoshalma')
insert into city (name) values ('Jászapáti')
insert into city (name) values ('Kunszentmiklós')
insert into city (name) values ('Dunavarsány')
insert into city (name) values ('Ercsi')
insert into city (name) values ('Kunszentmárton')
insert into city (name) values ('Erdőkertes')
insert into city (name) values ('Tamási')
insert into city (name) values ('Fehérgyarmat')
insert into city (name) values ('Polgár')
insert into city (name) values ('Nagykovácsi')
insert into city (name) values ('Tura')
insert into city (name) values ('Sándorfalva')
insert into city (name) values ('Jászárokszállás')
insert into city (name) values ('Nyíradony')
insert into city (name) values ('Kunhegyes')
insert into city (name) values ('Páty')
insert into city (name) values ('Üröm')
insert into city (name) values ('Füzesabony')
insert into city (name) values ('Őrbottyán')
insert into city (name) values ('Dévaványa')
insert into city (name) values ('Lenti')
insert into city (name) values ('Soltvadkert')
insert into city (name) values ('Nyergesújfalu')
insert into city (name) values ('Létavértes')
insert into city (name) values ('Kistelek')
insert into city (name) values ('Polgárdi')
insert into city (name) values ('Mogyoród')
insert into city (name) values ('Vésztő')
insert into city (name) values ('Zirc')
insert into city (name) values ('Ács')
insert into city (name) values ('Enying')
insert into city (name) values ('Ibrány')
insert into city (name) values ('Mindszent')
insert into city (name) values ('Nyírtelek')
insert into city (name) values ('Felsőzsolca')
insert into city (name) values ('Kerekegyháza')
insert into city (name) values ('Putnok')
insert into city (name) values ('Bácsalmás')
insert into city (name) values ('Téglás')
insert into city (name) values ('Győrújbarát')
insert into city (name) values ('Nagyecsed')
insert into city (name) values ('Zalaszentgrót')
insert into city (name) values ('Encs')
insert into city (name) values ('Fegyvernek')
insert into city (name) values ('Balkány')
insert into city (name) values ('Bátaszék')
insert into city (name) values ('Kozármisleny')
insert into city (name) values ('Taksony')
insert into city (name) values ('Aszód')
insert into city (name) values ('Szentlőrinc')
insert into city (name) values ('Martfů')
insert into city (name) values ('Mórahalom')
insert into city (name) values ('Solt')
insert into city (name) values ('Szabadszállás')
insert into city (name) values ('Tápiószecső')
insert into city (name) values ('Jánossomorja')
insert into city (name) values ('Újszász')
insert into city (name) values ('Sümeg')
insert into city (name) values ('Tótkomlós')
insert into city (name) values ('Kaba')
insert into city (name) values ('Pusztaszabolcs')
insert into city (name) values ('Berhida')
insert into city (name) values ('Tápiószele')
insert into city (name) values ('Balatonboglár')
insert into city (name) values ('Mezőkovácsháza')
insert into city (name) values ('Füzesgyarmat')
insert into city (name) values ('Jászfényszaru')
insert into city (name) values ('Tahitófalu')
insert into city (name) values ('Szécsény')
insert into city (name) values ('Dömsöd')
insert into city (name) values ('Nagyhalász')
insert into city (name) values ('Martonvásár')
insert into city (name) values ('Hosszúpályi')
insert into city (name) values ('Mezőcsát')
insert into city (name) values ('Kartal')
insert into city (name) values ('Zsámbék')
insert into city (name) values ('Izsák')
insert into city (name) values ('Lőrinci')
insert into city (name) values ('Velence')
insert into city (name) values ('Battonya')
insert into city (name) values ('Szada')
insert into city (name) values ('Jászladány')
insert into city (name) values ('Komádi')
insert into city (name) values ('Vámospércs')
insert into city (name) values ('Kisbér')
insert into city (name) values ('Kunmadaras')
insert into city (name) values ('Tát')
insert into city (name) values ('Szikszó')
insert into city (name) values ('Rákóczifalva')
insert into city (name) values ('Alsónémedi')
insert into city (name) values ('Tiszalök')
insert into city (name) values ('Csákvár')
insert into city (name) values ('Balatonlelle')
insert into city (name) values ('Tápiószentmárton')
insert into city (name) values ('Bugyi')
insert into city (name) values ('Jászkisér')
insert into city (name) values ('Egyek')
insert into city (name) values ('Tiszalúc')
insert into city (name) values ('Tiszaalpár')
insert into city (name) values ('Csenger')
insert into city (name) values ('Mezőhegyes')
insert into city (name) values ('Domaszék')
insert into city (name) values ('Újkígyós')
insert into city (name) values ('Nyírmada')
insert into city (name) values ('Nyékládháza')
insert into city (name) values ('Kondoros')
insert into city (name) values ('Lábatlan')
insert into city (name) values ('Fonyód')
insert into city (name) values ('Nagymaros')
insert into city (name) values ('Szentmártonkáta')
insert into city (name) values ('Emőd')
insert into city (name) values ('Kemecse')
insert into city (name) values ('Mélykút')
insert into city (name) values ('Örkény')
insert into city (name) values ('Onga')
insert into city (name) values ('Csurgó')
insert into city (name) values ('Tiszacsege')
insert into city (name) values ('Mezőfalva')
insert into city (name) values ('Szatymaz')
insert into city (name) values ('Csorvás')
insert into city (name) values ('Hévíz')
insert into city (name) values ('Nagyszénás')
insert into city (name) values ('Harkány')
insert into city (name) values ('Nagytarcsa')
insert into city (name) values ('Inárcs')
insert into city (name) values ('Rácalmás')
insert into city (name) values ('Helvécia')
insert into city (name) values ('Körösladány')
insert into city (name) values ('Lakitelek')
insert into city (name) values ('Sződliget')
insert into city (name) values ('Szabadbattyán')
insert into city (name) values ('Elek')
insert into city (name) values ('Dány')
insert into city (name) values ('Mikepércs')
insert into city (name) values ('Kótaj')
insert into city (name) values ('Aba')
insert into city (name) values ('Ebes')
insert into city (name) values ('Szegvár')
insert into city (name) values ('Környe')
insert into city (name) values ('Rakamaz')
insert into city (name) values ('Kóka')
insert into city (name) values ('Seregélyes')
insert into city (name) values ('Tószeg')
insert into city (name) values ('Kenderes')
insert into city (name) values ('Nyúl')
insert into city (name) values ('Délegyháza')
insert into city (name) values ('Tompa')
insert into city (name) values ('Tab')
insert into city (name) values ('Ceglédbercel')
insert into city (name) values ('Törtel')
insert into city (name) values ('Szendrő')
insert into city (name) values ('Záhony')
insert into city (name) values ('Pilisszentiván')
insert into city (name) values ('Csemő')
insert into city (name) values ('Demecser')
insert into city (name) values ('Devecser')
insert into city (name) values ('Szirmabesenyő')
insert into city (name) values ('Vasvár')
insert into city (name) values ('Mende')
insert into city (name) values ('Biharkeresztes')
insert into city (name) values ('Mándok')
insert into city (name) values ('Balatonfůzfő')
insert into city (name) values ('Abádszalók')
insert into city (name) values ('Etyek')
insert into city (name) values ('Tét')
insert into city (name) values ('Fadd')
insert into city (name) values ('Tokaj')
insert into city (name) values ('Bodajk')
insert into city (name) values ('Simontornya')
insert into city (name) values ('Tokod')
insert into city (name) values ('Nagyvenyim')
insert into city (name) values ('Pannonhalma')
insert into city (name) values ('Mályi')
insert into city (name) values ('Dombrád')
insert into city (name) values ('Doboz')
insert into city (name) values ('Telki')
insert into city (name) values ('Letenye')
insert into city (name) values ('Pécsvárad')
insert into city (name) values ('Földes')
insert into city (name) values ('Hernád')
insert into city (name) values ('Perkáta')
insert into city (name) values ('Baktalórántháza')
insert into city (name) values ('Cibakháza')
insert into city (name) values ('Adony')
insert into city (name) values ('Ásotthalom')
insert into city (name) values ('Fertőszentmiklós')
insert into city (name) values ('Ecser')
insert into city (name) values ('Bóly')
insert into city (name) values ('Mezőkeresztes')
insert into city (name) values ('Decs')
insert into city (name) values ('Nyíracsád')
insert into city (name) values ('Bábolna')
insert into city (name) values ('Verpelét')
insert into city (name) values ('Nyírábrány')
insert into city (name) values ('Dunavecse')
insert into city (name) values ('Szajol')
insert into city (name) values ('Ajak')
insert into city (name) values ('Nyáregyháza')
insert into city (name) values ('Pilisborosjenő')
insert into city (name) values ('Kiszombor')
insert into city (name) values ('Leányfalu')
insert into city (name) values ('Bag')
insert into city (name) values ('Sződ')
insert into city (name) values ('Napkor')
insert into city (name) values ('Gyenesdiás')
insert into city (name) values ('Hort')
insert into city (name) values ('Ballószög')
insert into city (name) values ('Békésszentandrás')
insert into city (name) values ('Taktaharkány')
insert into city (name) values ('Kápolnásnyék')
insert into city (name) values ('Arló')
insert into city (name) values ('Bük')
insert into city (name) values ('Kengyel')
insert into city (name) values ('Kállósemjén')
insert into city (name) values ('Felsőpakony')
insert into city (name) values ('Kál')
insert into city (name) values ('Vaja')
insert into city (name) values ('Felsőtárkány')
insert into city (name) values ('Gádoros')
insert into city (name) values ('Gávavencsellő')
insert into city (name) values ('Deszk')
insert into city (name) values ('Érsekvadkert')
insert into city (name) values ('Sükösd')
insert into city (name) values ('Medgyesegyháza')
insert into city (name) values ('Tuzsér')
insert into city (name) values ('Zagyvarékas')
insert into city (name) values ('Balástya')
insert into city (name) values ('Hernádnémeti')
insert into city (name) values ('Orgovány')
insert into city (name) values ('Farmos')
insert into city (name) values ('Tápióbicske')
insert into city (name) values ('Hegyeshalom')
insert into city (name) values ('Herend')
insert into city (name) values ('Hosszúhetény')
insert into city (name) values ('Hodász')
insert into city (name) values ('Baracs')
insert into city (name) values ('Fertőd')
insert into city (name) values ('Tóalmás')
insert into city (name) values ('Nyírpazony')
insert into city (name) values ('Csobánka')
insert into city (name) values ('Sóskút')
insert into city (name) values ('Tápiógyörgye')
insert into city (name) values ('Vép')
insert into city (name) values ('Vaskút')
insert into city (name) values ('Kétegyháza')
insert into city (name) values ('Bordány')
insert into city (name) values ('Nagybajom')
insert into city (name) values ('Zsombó')
insert into city (name) values ('Győrszemere')
insert into city (name) values ('Besenyszög')
insert into city (name) values ('Akasztó')
insert into city (name) values ('Ráckeresztúr')
insert into city (name) values ('Csepreg')
insert into city (name) values ('Harta')
insert into city (name) values ('Lébénymiklós')
insert into city (name) values ('Táborfalva')
insert into city (name) values ('Erdőtelek')
insert into city (name) values ('Öcsöd')
insert into city (name) values ('Sárosd')
insert into city (name) values ('Jászalsószentgyörgy')
insert into city (name) values ('Röszke')
insert into city (name) values ('Győrzámoly')
insert into city (name) values ('Nagyréde')
insert into city (name) values ('Bököny')
insert into city (name) values ('Halászi')
insert into city (name) values ('Abda')
insert into city (name) values ('Sajókaza')
insert into city (name) values ('Csolnok')
insert into city (name) values ('Nyírbogát')
insert into city (name) values ('Dunabogdány')
insert into city (name) values ('Ecséd')
insert into city (name) values ('Múcsony')
insert into city (name) values ('Borsodnádasd')
insert into city (name) values ('Abaújszántó')
insert into city (name) values ('Pákozd')
insert into city (name) values ('Gönyů')
insert into city (name) values ('Kakucs')
insert into city (name) values ('Csabrendek')
insert into city (name) values ('Hajdúszovát')
insert into city (name) values ('Hévizgyörk')
insert into city (name) values ('Gomba')
insert into city (name) values ('Zalalövő')
insert into city (name) values ('Öttevény')
insert into city (name) values ('Dunapataj')
insert into city (name) values ('Cigánd')
insert into city (name) values ('Ópályi')
insert into city (name) values ('Lengyeltóti')
insert into city (name) values ('Vértesszőlős')
insert into city (name) values ('Nagymágocs')
insert into city (name) values ('Üllés')
insert into city (name) values ('Lepsény')
insert into city (name) values ('Sárszentmihály')
insert into city (name) values ('Földeák')
insert into city (name) values ('Balatonszabadi')
insert into city (name) values ('Sárrétudvari')
insert into city (name) values ('Zalakomár')
insert into city (name) values ('Bakonycsernye')
insert into city (name) values ('Levelek')
insert into city (name) values ('Nyírbéltek')
insert into city (name) values ('Nagyigmánd')
insert into city (name) values ('Pilisszántó')
insert into city (name) values ('Boldog')
insert into city (name) values ('Bélapátfalva')
insert into city (name) values ('Sásd')
insert into city (name) values ('Cserszegtomaj')
insert into city (name) values ('Tiszabura')
insert into city (name) values ('Pátroha')
insert into city (name) values ('Poroszló')
insert into city (name) values ('Kisköre')
insert into city (name) values ('Karácsond')
insert into city (name) values ('Tiszadob')
insert into city (name) values ('Kocsord')
insert into city (name) values ('Tarcal')
insert into city (name) values ('Hőgyész')
insert into city (name) values ('Hajmáskér')
insert into city (name) values ('Hajós')
insert into city (name) values ('Nyírbogdány')
insert into city (name) values ('Gyöngyössolymos')
insert into city (name) values ('Biharnagybajom')
insert into city (name) values ('Harka')
insert into city (name) values ('Dánszentmiklós')
insert into city (name) values ('Sajólád')
insert into city (name) values ('Iváncsa')
insert into city (name) values ('Jászjákóhalma')
insert into city (name) values ('Csanádpalota')
insert into city (name) values ('Tápiószőlős')
insert into city (name) values ('Gesztely')
insert into city (name) values ('Sajóbábony')
insert into city (name) values ('Baj')
insert into city (name) values ('Tornyospálca')
insert into city (name) values ('Diósjenő')
insert into city (name) values ('Érsekcsanád')
insert into city (name) values ('Dusnok')
insert into city (name) values ('Bölcske')
insert into city (name) values ('Szalkszentmárton')
insert into city (name) values ('Porcsalma')
insert into city (name) values ('Szakoly')
insert into city (name) values ('Újhartyán')
insert into city (name) values ('Zákányszék')
insert into city (name) values ('Nagyhegyes')
insert into city (name) values ('Szentgál')
insert into city (name) values ('Nyírmeggyes')
insert into city (name) values ('Gencsapáti')
insert into city (name) values ('Megyaszó')
insert into city (name) values ('Bőcs')
insert into city (name) values ('Rétság')
insert into city (name) values ('Tass')
insert into city (name) values ('Nyírlugos')
insert into city (name) values ('Herceghalom')
insert into city (name) values ('Nemesvámos')
insert into city (name) values ('Sárisáp')
insert into city (name) values ('Recsk')
insert into city (name) values ('Baracska')
insert into city (name) values ('Iregszemcse')
insert into city (name) values ('Kunágota')
insert into city (name) values ('Adács')
insert into city (name) values ('Madaras')
insert into city (name) values ('Pocsaj')
insert into city (name) values ('Beled')
insert into city (name) values ('Kóny')
insert into city (name) values ('Báránd')
insert into city (name) values ('Tápióság')
insert into city (name) values ('Répcelak')
insert into city (name) values ('Jászkarajenő')
insert into city (name) values ('Tiszakeszi')
insert into city (name) values ('Rajka')
insert into city (name) values ('Andornaktálya')
insert into city (name) values ('Karancslapujtő')
insert into city (name) values ('Ják')
insert into city (name) values ('Cece')
insert into city (name) values ('Besenyőtelek')
insert into city (name) values ('Petőfibánya')
insert into city (name) values ('Lovasberény')
insert into city (name) values ('Bugac')
insert into city (name) values ('Ostoros')
insert into city (name) values ('Nagydorog')
insert into city (name) values ('Balatonkenese')
insert into city (name) values ('Tiszaeszlár')
insert into city (name) values ('Berzence')
insert into city (name) values ('Szob')
insert into city (name) values ('Táplánszentkereszt')
insert into city (name) values ('Tarján')
insert into city (name) values ('Okány')
insert into city (name) values ('Jakabszállás')
insert into city (name) values ('Dunaszentgyörgy')
insert into city (name) values ('Újszilvás')
insert into city (name) values ('Sárkeresztúr')
insert into city (name) values ('Ófehértó')
insert into city (name) values ('Úri')
insert into city (name) values ('Bagamér')
insert into city (name) values ('Abasár')
insert into city (name) values ('Galgahéviz')
insert into city (name) values ('Csanádapáca')
insert into city (name) values ('Kesztölc')
insert into city (name) values ('Szigetmonostor')
insert into city (name) values ('Kocs')
insert into city (name) values ('Gyöngyöshalász')
insert into city (name) values ('Rudabánya')
insert into city (name) values ('Segesd')
insert into city (name) values ('Rábapatona')
insert into city (name) values ('Csanytelek')
insert into city (name) values ('Prügy')
insert into city (name) values ('Forró')
insert into city (name) values ('Jánosháza')
insert into city (name) values ('Bekecs')
insert into city (name) values ('Sellye')
insert into city (name) values ('Gyöngyöspata')
insert into city (name) values ('Tiszanána')
insert into city (name) values ('Kisláng')
insert into city (name) values ('Jászszentlászló')
insert into city (name) values ('Bácsbokod')
insert into city (name) values ('Apc')
insert into city (name) values ('Mezőzombor')
insert into city (name) values ('Mány')
insert into city (name) values ('Kadarkút')
insert into city (name) values ('Kaposmérő')
insert into city (name) values ('Tiszakarád')
insert into city (name) values ('Kelebia')
insert into city (name) values ('Úrhida')
insert into city (name) values ('Tunyogmatolcs')
insert into city (name) values ('Valkó')
insert into city (name) values ('Szentistván')
insert into city (name) values ('Szabadkígyós')
insert into city (name) values ('Zamárdi')
insert into city (name) values ('Pusztavám')
insert into city (name) values ('Fényeslitke')
insert into city (name) values ('Ruzsa')
insert into city (name) values ('Jászszentandrás')
insert into city (name) values ('Kosd')
insert into city (name) values ('Vál')
insert into city (name) values ('Békéssámson')
insert into city (name) values ('Lánycsók')
insert into city (name) values ('Pér')
insert into city (name) values ('Nyírkarász')
insert into city (name) values ('Gyöngyöstarján')
insert into city (name) values ('Kisszállás')
insert into city (name) values ('Péteri')
insert into city (name) values ('Jánoshida')
insert into city (name) values ('Káloz')
insert into city (name) values ('Görbeháza')
insert into city (name) values ('Zsámbok')
insert into city (name) values ('Maklár')
insert into city (name) values ('Boldva')
insert into city (name) values ('Őcsény')
insert into city (name) values ('Ónod')
insert into city (name) values ('Szigetcsép')
insert into city (name) values ('Piliscsév')
insert into city (name) values ('Nyárlőrinc')
insert into city (name) values ('Tarpa')
insert into city (name) values ('Szank')
insert into city (name) values ('Köröstarcsa')
insert into city (name) values ('Apagy')
insert into city (name) values ('Kerecsend')
insert into city (name) values ('Beremend')
insert into city (name) values ('Naszály')
insert into city (name) values ('Verőcemaros')
insert into city (name) values ('Magyarbánhegyes')
insert into city (name) values ('Pócsmegyer')
insert into city (name) values ('Döge')
insert into city (name) values ('Buj')
insert into city (name) values ('Töltéstava')
insert into city (name) values ('Kimle')
insert into city (name) values ('Villány')
insert into city (name) values ('Kéthely')
insert into city (name) values ('Előszállás')
insert into city (name) values ('Nagymányok')
insert into city (name) values ('Gara')
insert into city (name) values ('Nagybaracska')
insert into city (name) values ('Böhönye')
insert into city (name) values ('Fertőrákos')
insert into city (name) values ('Nyírmihálydi')
insert into city (name) values ('Cserkeszőlő')
insert into city (name) values ('Szigetszentmárton')
insert into city (name) values ('Tiszadada')
insert into city (name) values ('Pellérd')
insert into city (name) values ('Forráskút')
insert into city (name) values ('Lajoskomárom')
insert into city (name) values ('Szászvár')
insert into city (name) values ('Sáránd')
insert into city (name) values ('Nagydobos')
insert into city (name) values ('Szedres')
insert into city (name) values ('Mád')
insert into city (name) values ('Öskü')
insert into city (name) values ('Pincehely')
insert into city (name) values ('Tengelic')
insert into city (name) values ('Császártöltés')
insert into city (name) values ('Nyírcsaholy')
insert into city (name) values ('Balatonföldvár')
insert into city (name) values ('Mágocs')
insert into city (name) values ('Dég')
insert into city (name) values ('Konyár')
insert into city (name) values ('Buják')
insert into city (name) values ('Sajószöged')
insert into city (name) values ('Bucsa')
insert into city (name) values ('Ópusztaszer')
insert into city (name) values ('Kántorjánosi')
insert into city (name) values ('Vonyarcvashegy')
insert into city (name) values ('Litér')
insert into city (name) values ('Pázmánd')
insert into city (name) values ('Máriapócs')
insert into city (name) values ('Mérk')
insert into city (name) values ('Bogyiszló')
insert into city (name) values ('Bőny')
insert into city (name) values ('Badacsonytomaj')
insert into city (name) values ('Ágfalva')
insert into city (name) values ('Zámoly')
insert into city (name) values ('Monostorpályi')
insert into city (name) values ('Nagyrábé')
insert into city (name) values ('Pilisszentkereszt')
insert into city (name) values ('Mocsa')
insert into city (name) values ('Ádánd')
insert into city (name) values ('Sajóvámos')
insert into city (name) values ('Nagyoroszi')
insert into city (name) values ('Csány')
insert into city (name) values ('Tiszabő')
insert into city (name) values ('Domony')
insert into city (name) values ('Fülöpszállás')
insert into city (name) values ('Mezőszilas')
insert into city (name) values ('Jászdózsa')
insert into city (name) values ('Jobbágyi')
insert into city (name) values ('Méhkerék')
insert into city (name) values ('Szabadegyháza')
insert into city (name) values ('Kistokaj')
insert into city (name) values ('Tordas')
insert into city (name) values ('Kópháza')
insert into city (name) values ('Koroncó')
insert into city (name) values ('Becsehely')
insert into city (name) values ('Bokod')
insert into city (name) values ('Iklad')
insert into city (name) values ('Szendrőlád')
insert into city (name) values ('Kunfehértó')
insert into city (name) values ('Perbál')
insert into city (name) values ('Kevermes')
insert into city (name) values ('Gyönk')
insert into city (name) values ('Almásfüzitő')
insert into city (name) values ('Aranyosapáti')
insert into city (name) values ('Nyírgyulaj')
insert into city (name) values ('Csörögimajor')
insert into city (name) values ('Bősárkány')
insert into city (name) values ('Parád')
insert into city (name) values ('Bercel')
insert into city (name) values ('Zomba')
insert into city (name) values ('Romhány')
insert into city (name) values ('Dombegyház')
insert into city (name) values ('Maroslele')
insert into city (name) values ('Hidas')
insert into city (name) values ('Nyírmártonfalva')
insert into city (name) values ('Pétervására')
insert into city (name) values ('Tyukod')
insert into city (name) values ('Szany')
insert into city (name) values ('Süttő')
insert into city (name) values ('Nyírtass')
insert into city (name) values ('Tiszaszentimre')
insert into city (name) values ('Úrkút')
insert into city (name) values ('Harsány')
insert into city (name) values ('Bátya')
insert into city (name) values ('Apostag')
insert into city (name) values ('Nyírkáta')
insert into city (name) values ('Szomód')
insert into city (name) values ('Vácszentlászló')
insert into city (name) values ('Nagycenk')
insert into city (name) values ('Dunaszeg')
insert into city (name) values ('Tiszapüspöki')
insert into city (name) values ('Nagykozár')
insert into city (name) values ('Baks')
insert into city (name) values ('Ősi')
insert into city (name) values ('Kecskéd')
insert into city (name) values ('Hajdubagos')
insert into city (name) values ('Zagyvaszántó')
insert into city (name) values ('Kompolt')
insert into city (name) values ('Egerszalók')
insert into city (name) values ('Székkutas')
insert into city (name) values ('Pilismarót')
insert into city (name) values ('Rád')
insert into city (name) values ('Hercegszántó')
insert into city (name) values ('Fábiánsebestyén')
insert into city (name) values ('Gönc')
insert into city (name) values ('Csengőd')
insert into city (name) values ('Vasad')
insert into city (name) values ('Szigetújfalu')
insert into city (name) values ('Nyírvasvári')
insert into city (name) values ('Bogács')
insert into city (name) values ('Encsencs')
insert into city (name) values ('Domoszló')
insert into city (name) values ('Csengele')
insert into city (name) values ('Balatonszárszó')
insert into city (name) values ('Szamosszeg')
insert into city (name) values ('Döbrököz')
insert into city (name) values ('Anarcs')
insert into city (name) values ('Budajenő')
insert into city (name) values ('Iszkaszentgyörgy')
insert into city (name) values ('Taktaszada')
insert into city (name) values ('Gyulaháza')
insert into city (name) values ('Alattyán')
insert into city (name) values ('Zalakaros')
insert into city (name) values ('Kék')
insert into city (name) values ('Gégény')
insert into city (name) values ('Lábod')
insert into city (name) values ('Dávod')
insert into city (name) values ('Mátraverebély')
insert into city (name) values ('Kaszaper')
insert into city (name) values ('Mátraderecske')
insert into city (name) values ('Vácrátót')
insert into city (name) values ('Berekböszörmény')
insert into city (name) values ('Torony')
insert into city (name) values ('Csévharaszt')
insert into city (name) values ('Taszár')
insert into city (name) values ('Pánd')
insert into city (name) values ('Csökmő')
insert into city (name) values ('Rákócziújfalu')
insert into city (name) values ('Vámosgyörk')
insert into city (name) values ('Alap')
insert into city (name) values ('Szurdokpüspöki')
insert into city (name) values ('Jászfelsőszentgyörgy')
insert into city (name) values ('Écs')
insert into city (name) values ('Fehérvárcsurgó')
insert into city (name) values ('Újszentiván')
insert into city (name) values ('Hejőbába')
insert into city (name) values ('Kisléta')
insert into city (name) values ('Szihalom')
insert into city (name) values ('Farád')
insert into city (name) values ('Nyirád')
insert into city (name) values ('Szentlőrinckáta')
insert into city (name) values ('Tállya')
insert into city (name) values ('Noszvaj')
insert into city (name) values ('Madocsa')
insert into city (name) values ('Tiszabezdéd')
insert into city (name) values ('Nyársapát')
insert into city (name) values ('Szokolya')
insert into city (name) values ('Rózsaszentmárton')
insert into city (name) values ('Kömlő')
insert into city (name) values ('Császár')
insert into city (name) values ('Heréd')
insert into city (name) values ('Csetény')
insert into city (name) values ('Karancskeszi')
insert into city (name) values ('Mátraterenye')
insert into city (name) values ('Dunakiliti')
insert into city (name) values ('Szentkirály')
insert into city (name) values ('Bajna')
insert into city (name) values ('Járdánháza')
insert into city (name) values ('Szentkirályszabadja')
insert into city (name) values ('Rimóc')
insert into city (name) values ('Aszaló')
insert into city (name) values ('Kocsér')
insert into city (name) values ('Visegrád')
insert into city (name) values ('Kálmánháza')
insert into city (name) values ('Tar')
insert into city (name) values ('Kazár')
insert into city (name) values ('Ágasegyháza')
insert into city (name) values ('Piricse')
insert into city (name) values ('Balatonfenyves')
insert into city (name) values ('Sármellék')
insert into city (name) values ('Ikrény')
insert into city (name) values ('Soponya')
insert into city (name) values ('Tarnaőrs')
insert into city (name) values ('Ököritófülpös')
insert into city (name) values ('Karcsa')
insert into city (name) values ('Tiszabercel')
insert into city (name) values ('Leányvár')
insert into city (name) values ('Tolcsva')
insert into city (name) values ('Sirok')
insert into city (name) values ('Felcsút')
insert into city (name) values ('Levél')
insert into city (name) values ('Tatárszentgyörgy')
insert into city (name) values ('Bócsa')
insert into city (name) values ('Ságvár')
insert into city (name) values ('Pap')
insert into city (name) values ('Tiszanagyfalu')
insert into city (name) values ('Kesznyéten')
insert into city (name) values ('Halmaj')
insert into city (name) values ('Galgamácsa')
insert into city (name) values ('Pálmonostora')
insert into city (name) values ('Dunaszekcső')
insert into city (name) values ('Máriakálnok')
insert into city (name) values ('Nagyszentjános')
insert into city (name) values ('Tarnalelesz')
insert into city (name) values ('Csór')
insert into city (name) values ('Ikervár')
insert into city (name) values ('Nagycserkesz')
insert into city (name) values ('Tázlár')
insert into city (name) values ('Nemesnádudvar')
insert into city (name) values ('Vértesacsa')
insert into city (name) values ('Ricse')
insert into city (name) values ('Váchartyán')
insert into city (name) values ('Csabacsůd')
insert into city (name) values ('Balatonszemes')
insert into city (name) values ('Nyírtura')
insert into city (name) values ('Csopak')
insert into city (name) values ('Felsőszentiván')
insert into city (name) values ('Győrújfalu')
insert into city (name) values ('Csákánydoroszló')
insert into city (name) values ('Somogyvár')
insert into city (name) values ('Bakonyszentlászló')
insert into city (name) values ('Sály')
insert into city (name) values ('Nagyvázsony')
insert into city (name) values ('Fülöp')
insert into city (name) values ('Fábiánháza')
insert into city (name) values ('Izsófalva')
insert into city (name) values ('Jánkmajtis')
insert into city (name) values ('Enese')
insert into city (name) values ('Petneháza')
insert into city (name) values ('Csávoly')
insert into city (name) values ('Besnyő')
insert into city (name) values ('Tinnye')
insert into city (name) values ('Nádasdladány')
insert into city (name) values ('Méra')
insert into city (name) values ('Zsadány')
insert into city (name) values ('Tác')
insert into city (name) values ('Németkér')
insert into city (name) values ('Geszteréd')
insert into city (name) values ('Mosonszolnok')
insert into city (name) values ('Ászár')
insert into city (name) values ('Tiszasziget')
insert into city (name) values ('Vajszló')
insert into city (name) values ('Tömörkény')
insert into city (name) values ('Újlengyel')
insert into city (name) values ('Bükkábrány')
insert into city (name) values ('Katymár')
insert into city (name) values ('Vasmegyer')
insert into city (name) values ('Szabolcsveresmart')
insert into city (name) values ('Jászboldogháza')
insert into city (name) values ('Olaszliszka')
insert into city (name) values ('Báta')
insert into city (name) values ('Kisgyőr')
insert into city (name) values ('Szederkény')
insert into city (name) values ('Nógrádmegyer')
insert into city (name) values ('Pócspetri')
insert into city (name) values ('Mátranovák')
insert into city (name) values ('Érpatak')
insert into city (name) values ('Zalaapáti')
insert into city (name) values ('Győrladamér')
insert into city (name) values ('Hernádkak')
insert into city (name) values ('Lőkösháza')
insert into city (name) values ('Pátka')
insert into city (name) values ('Pusztaföldvár')
insert into city (name) values ('Vámosszabadi')
insert into city (name) values ('Tarnaméra')
insert into city (name) values ('Kakasd')
insert into city (name) values ('Álmosd')
insert into city (name) values ('Csomád')
insert into city (name) values ('Kunszállás')
insert into city (name) values ('Dudar')
insert into city (name) values ('Rábapaty')
insert into city (name) values ('Kaposfő')
insert into city (name) values ('Murakeresztúr')
insert into city (name) values ('Szár')
insert into city (name) values ('Felsőörs')
insert into city (name) values ('Alsóörs')
insert into city (name) values ('Monok')
insert into city (name) values ('Ormosi Tanya')
insert into city (name) values ('Pacsa')
insert into city (name) values ('Bana')
insert into city (name) values ('Szomolya')
insert into city (name) values ('Vámosmikola')
insert into city (name) values ('Fajsz')
insert into city (name) values ('Szilvásvárad')
insert into city (name) values ('Tardosbánya')
insert into city (name) values ('Nagyfüged')
insert into city (name) values ('Mezőtárkány')
insert into city (name) values ('Kőtelek')
insert into city (name) values ('Ozora')
insert into city (name) values ('Mezőnyárád')
insert into city (name) values ('Varsány')
insert into city (name) values ('Dunasziget')
insert into city (name) values ('Bajót')
insert into city (name) values ('Hangony')
insert into city (name) values ('Ladánybene')
insert into city (name) values ('Jásztelek')
insert into city (name) values ('Csépa')
insert into city (name) values ('Istenmezeje')
insert into city (name) values ('Győrtelek')
insert into city (name) values ('Szerep')
insert into city (name) values ('Majosháza')
insert into city (name) values ('Miske')
insert into city (name) values ('Palotáshalom')
insert into city (name) values ('Somogyjád')
insert into city (name) values ('Hegykő')
insert into city (name) values ('Balatonszentgyörgy')
insert into city (name) values ('Derekegyház')
insert into city (name) values ('Nagykörů')
insert into city (name) values ('Vácduka')
insert into city (name) values ('Tényő')
insert into city (name) values ('Kurityán')
insert into city (name) values ('Tiszakanyár')
insert into city (name) values ('Bak')
insert into city (name) values ('Szůcsi')
insert into city (name) values ('Somogyszob')
insert into city (name) values ('Tiszajenő')
insert into city (name) values ('Szepetnek')
insert into city (name) values ('Pálfa')
insert into city (name) values ('Karád')
insert into city (name) values ('Csokonyavisonta')
insert into city (name) values ('Gellénháza')
insert into city (name) values ('Mátraszőlős')
insert into city (name) values ('Tiszatenyő')
insert into city (name) values ('Zsáka')
insert into city (name) values ('Szatmárcseke')
insert into city (name) values ('Csólyospálos')
insert into city (name) values ('Dunaalmás')
insert into city (name) values ('Magyaralmás')
insert into city (name) values ('Türje')
insert into city (name) values ('Gyöngyösoroszi')
insert into city (name) values ('Öreglak')
insert into city (name) values ('Szendehely')
insert into city (name) values ('Pusztadobos')
insert into city (name) values ('Tiszaroff')
insert into city (name) values ('Nagylóc')
insert into city (name) values ('Tiszavárkony')
insert into city (name) values ('Karancsalja')
insert into city (name) values ('Dédestapolcsány')
insert into city (name) values ('Sárkeresztes')
insert into city (name) values ('Kékcse')
insert into city (name) values ('Darnózseli')
insert into city (name) values ('Penc')
insert into city (name) values ('Foktő')
insert into city (name) values ('Ramocsaháza')
insert into city (name) values ('Kaposszekcső')
insert into city (name) values ('Alsóvadász')
insert into city (name) values ('Pusztamonostor')
insert into city (name) values ('Babócsa')
insert into city (name) values ('Sarkadkeresztúr')
insert into city (name) values ('Legyesbénye')
insert into city (name) values ('Balatonkeresztúr')
insert into city (name) values ('Papkeszi')
insert into city (name) values ('Balotaszállás')
insert into city (name) values ('Drégelypalánk')
insert into city (name) values ('Görcsöny')
insert into city (name) values ('Sajókeresztúr')
insert into city (name) values ('Kölesd')
insert into city (name) values ('Bükkaranyos')
insert into city (name) values ('Vaszar')
insert into city (name) values ('Bátmonostor')
insert into city (name) values ('Újszentmargita')
insert into city (name) values ('Hortobágy')
insert into city (name) values ('Győrság')
insert into city (name) values ('Kápolna')
insert into city (name) values ('Gyermely')
insert into city (name) values ('Kötegyán')
insert into city (name) values ('Vilmány')
insert into city (name) values ('Kutas')
insert into city (name) values ('Kunadacs')
insert into city (name) values ('Nagyberki')
insert into city (name) values ('Kálló')
insert into city (name) values ('Nagyvarsány')
insert into city (name) values ('Bakonyszombathely')
insert into city (name) values ('Alcsútdoboz')
insert into city (name) values ('Kincses')
insert into city (name) values ('Söjtör')
insert into city (name) values ('Pereszteg')
insert into city (name) values ('Szákszend')
insert into city (name) values ('Tiszasüly')
insert into city (name) values ('Kőszárhegy')
insert into city (name) values ('Kübekháza')
insert into city (name) values ('Nagysáp')
insert into city (name) values ('Tárkány')
insert into city (name) values ('Tiszapalkonya')
insert into city (name) values ('Tiszatarján')
insert into city (name) values ('Alsópáhok')
insert into city (name) values ('Őr')
insert into city (name) values ('Kunbaja')
insert into city (name) values ('Egerbakta')
insert into city (name) values ('Novajidrány')
insert into city (name) values ('Tiszakürt')
insert into city (name) values ('Tetétlen')
insert into city (name) values ('Kölcse')
insert into city (name) values ('Biri')
insert into city (name) values ('Dunaegyháza')
insert into city (name) values ('Lövő')
insert into city (name) values ('Sukoró')
insert into city (name) values ('Tiszatelek')
insert into city (name) values ('Nagyharsány')
insert into city (name) values ('Petőfiszállás')
insert into city (name) values ('Csátalja')
insert into city (name) values ('Püspökhatvan')
insert into city (name) values ('Nógrád')
insert into city (name) values ('Pácin')
insert into city (name) values ('Magyarcsanád')
insert into city (name) values ('Mesztegnyő')
insert into city (name) values ('Acsa')
insert into city (name) values ('Végegyháza')
insert into city (name) values ('Ugod')
insert into city (name) values ('Sajópetri')
insert into city (name) values ('Nagykamarás')
insert into city (name) values ('Sényő')
insert into city (name) values ('Tiszaörs')
insert into city (name) values ('Dejtár')
insert into city (name) values ('Nagykereki')
insert into city (name) values ('Köröm')
insert into city (name) values ('Kisapostag')
insert into city (name) values ('Etes')
insert into city (name) values ('Bánhorváti')
insert into city (name) values ('Tihany')
insert into city (name) values ('Pusztaszer')
insert into city (name) values ('Tibolddaróc')
insert into city (name) values ('Pély')
insert into city (name) values ('Bodroghalom')
insert into city (name) values ('Sárszentágota')
insert into city (name) values ('Csókakő')
insert into city (name) values ('Réde')
insert into city (name) values ('Szakály')
insert into city (name) values ('Pusztavacs')
insert into city (name) values ('Tevel')
insert into city (name) values ('Szügy')
insert into city (name) values ('Vasszécseny')
insert into city (name) values ('Mernye')
insert into city (name) values ('Buzsák')
insert into city (name) values ('Látrány')
insert into city (name) values ('Esztár')
insert into city (name) values ('Novaj')
insert into city (name) values ('Bánréve')
insert into city (name) values ('Pitvaras')
insert into city (name) values ('Kőröshegy')
insert into city (name) values ('Tótvázsony')
insert into city (name) values ('Telekgerendás')
insert into city (name) values ('Sé')
insert into city (name) values ('Szeremle')
insert into city (name) values ('Verseg')
insert into city (name) values ('Egercsehi')
insert into city (name) values ('Szil')
insert into city (name) values ('Tök')
insert into city (name) values ('Vizslás')
insert into city (name) values ('Vajdácska')
insert into city (name) values ('Véménd')
insert into city (name) values ('Fertőszéplak')
insert into city (name) values ('Balatonendréd')
insert into city (name) values ('Borota')
insert into city (name) values ('Nádasd')
insert into city (name) values ('Nagyberény')
insert into city (name) values ('Igal')
insert into city (name) values ('Vértessomló')
insert into city (name) values ('Bezenye')
insert into city (name) values ('Jármi')
insert into city (name) values ('Balatonfőkajár')
insert into city (name) values ('Városlőd')
insert into city (name) values ('Nagykarácsony')
insert into city (name) values ('Somberek')
insert into city (name) values ('Vitnyéd')
insert into city (name) values ('Mártély')
insert into city (name) values ('Jenő')
insert into city (name) values ('Sajóörös')
insert into city (name) values ('Timár')
insert into city (name) values ('Bágyogszovát')
insert into city (name) values ('Tiszabecs')
insert into city (name) values ('Gyarmat')
insert into city (name) values ('Kocsola')
insert into city (name) values ('Halmajugra')
insert into city (name) values ('Soltszentimre')
insert into city (name) values ('Börcs')
insert into city (name) values ('Karancsság')
insert into city (name) values ('Boconád')
insert into city (name) values ('Iharosberény')
insert into city (name) values ('Taktakenéz')
insert into city (name) values ('Bagod')
insert into city (name) values ('Neszmély')
insert into city (name) values ('Bénye')
insert into city (name) values ('Kétsoprony')
insert into city (name) values ('Egyházasrádóc')
insert into city (name) values ('Mezőszentgyörgy')
insert into city (name) values ('Kajárpéc')
insert into city (name) values ('Galambok')
insert into city (name) values ('Iván')
insert into city (name) values ('Eperjeske')
insert into city (name) values ('Homokmégy')
insert into city (name) values ('Kővágószőlős')
insert into city (name) values ('Kismarja')
insert into city (name) values ('Komoró')
insert into city (name) values ('Szigetbecse')
insert into city (name) values ('Sopronkövesd')
insert into city (name) values ('Kajdacs')
insert into city (name) values ('Nárai')
insert into city (name) values ('Gyüre')
insert into city (name) values ('Gyúró')
insert into city (name) values ('Szőlősgyörök')
insert into city (name) values ('Pogány')
insert into city (name) values ('Dalmand')
insert into city (name) values ('Sióagárd')
insert into city (name) values ('Hédervár')
insert into city (name) values ('Magyarkeszi')
insert into city (name) values ('Rohod')
insert into city (name) values ('Rum')
insert into city (name) values ('Kunsziget')
insert into city (name) values ('Rém')
insert into city (name) values ('Paszab')
insert into city (name) values ('Keszü')
insert into city (name) values ('Ilk')
insert into city (name) values ('Zebegény')
insert into city (name) values ('Szirák')
insert into city (name) values ('Nagybánhegyes')
insert into city (name) values ('Váncsod')
insert into city (name) values ('Igrici')
insert into city (name) values ('Bakonybél')
insert into city (name) values ('Márkó')
insert into city (name) values ('Szakmár')
insert into city (name) values ('Ináncs')
insert into city (name) values ('Endrefalva')
insert into city (name) values ('Vanyarc')
insert into city (name) values ('Tarnazsadány')
insert into city (name) values ('Alsószentmárton')
insert into city (name) values ('Pilisszentlászló')
insert into city (name) values ('Gyömöre')
insert into city (name) values ('Bükkszentkereszt')
insert into city (name) values ('Tard')
insert into city (name) values ('Zalahaláp')
insert into city (name) values ('Kislőd')
insert into city (name) values ('Ravazd')
insert into city (name) values ('Gerjen')
insert into city (name) values ('Somogysárd')
insert into city (name) values ('Lovászi')
insert into city (name) values ('Tenk')
insert into city (name) values ('Bakonszeg')
insert into city (name) values ('Borsodszentgyörgy')
insert into city (name) values ('Hencida')
insert into city (name) values ('Pusztazámor')
insert into city (name) values ('Kehidakustány')
insert into city (name) values ('Gerendás')
insert into city (name) values ('Nyírcsászári')
insert into city (name) values ('Sarud')
insert into city (name) values ('Csabdi')
insert into city (name) values ('Mezőcsokonya')
insert into city (name) values ('Hetes')
insert into city (name) values ('Súr')
insert into city (name) values ('Mezőszemere')
insert into city (name) values ('Tarany')
insert into city (name) values ('Magyarpolány')
insert into city (name) values ('Révfülöp')
insert into city (name) values ('Ecseg')
insert into city (name) values ('Nagyiván')
insert into city (name) values ('Furta')
insert into city (name) values ('Kenézlő')
insert into city (name) values ('Páhi')
insert into city (name) values ('Rezi')
insert into city (name) values ('Pápateszér')
insert into city (name) values ('Hidasnémeti')
insert into city (name) values ('Detk')
insert into city (name) values ('Makád')
insert into city (name) values ('Csákberény')
insert into city (name) values ('Inke')
insert into city (name) values ('Ecsegfalva')
insert into city (name) values ('Szalonna')
insert into city (name) values ('Szabolcsbáka')
insert into city (name) values ('Őriszentpéter')
insert into city (name) values ('Újléta')
insert into city (name) values ('Nagyesztergár')
insert into city (name) values ('Regöly')
insert into city (name) values ('Felgyő')
insert into city (name) values ('Balatonvilágos')
insert into city (name) values ('Hejőpapi')
insert into city (name) values ('Szuhogy')
insert into city (name) values ('Tataháza')
insert into city (name) values ('Szalánta')
insert into city (name) values ('Juta')
insert into city (name) values ('Borsodszirák')
insert into city (name) values ('Kisar')
insert into city (name) values ('Páka')
insert into city (name) values ('Kurd')
insert into city (name) values ('Máza')
insert into city (name) values ('Mezőladány')
insert into city (name) values ('Teskánd')
insert into city (name) values ('Halimba')
insert into city (name) values ('Gyöngyösfalu')
insert into city (name) values ('Sáta')
insert into city (name) values ('Lovászpatona')
insert into city (name) values ('Tiszaszentmárton')
insert into city (name) values ('Monostorapáti')
insert into city (name) values ('Parasznya')
insert into city (name) values ('Babót')
insert into city (name) values ('Gérce')
insert into city (name) values ('Bocfölde')
insert into city (name) values ('Vállaj')
insert into city (name) values ('Boldogkőváralja')
insert into city (name) values ('Lesencetomaj')
insert into city (name) values ('Letkés')
insert into city (name) values ('Visonta')
insert into city (name) values ('Dömös')
insert into city (name) values ('Ároktő')
insert into city (name) values ('Visznek')
insert into city (name) values ('Nyírgelse')
insert into city (name) values ('Szentpéterszeg')
insert into city (name) values ('Sajóhidvég')
insert into city (name) values ('Bodrogkeresztúr')
insert into city (name) values ('Somlóvásárhely')
insert into city (name) values ('Homokszentgyörgy')
insert into city (name) values ('Balogunyom')
insert into city (name) values ('Cered')
insert into city (name) values ('Nyíribrony')
insert into city (name) values ('Tépe')
insert into city (name) values ('Sokorópátka')
insert into city (name) values ('Várdomb')
insert into city (name) values ('Nagykónyi')
insert into city (name) values ('Gelse')
insert into city (name) values ('Bárdudvarnok')
insert into city (name) values ('Berzék')
insert into city (name) values ('Murony')
insert into city (name) values ('Görgeteg')
insert into city (name) values ('Kömlőd')
insert into city (name) values ('Hernádvécse')
insert into city (name) values ('Bácsborsód')
insert into city (name) values ('Lukácsháza')
insert into city (name) values ('Tótszerdahely')
insert into city (name) values ('Balatonberény')
insert into city (name) values ('Erdőbénye')
insert into city (name) values ('Bódvaszilas')
insert into city (name) values ('Andocs')
insert into city (name) values ('Nagyrécse')
insert into city (name) values ('Nézsa')
insert into city (name) values ('Varbó')
insert into city (name) values ('Zákány')
insert into city (name) values ('Csököly')
insert into city (name) values ('Káld')
insert into city (name) values ('Szalaszend')
insert into city (name) values ('Beloiannisz')
insert into city (name) values ('Pálháza')
insert into city (name) values ('Medgyesbodzás')
insert into city (name) values ('Balatongyörök')
insert into city (name) values ('Sárszentlőrinc')
insert into city (name) values ('Mezőgyán')
insert into city (name) values ('Rétközberencs')
insert into city (name) values ('Veszprémvarsány')
insert into city (name) values ('Dorogháza')
insert into city (name) values ('Balaton')
insert into city (name) values ('Szomor')
insert into city (name) values ('Vásárosdombó')
insert into city (name) values ('Székely')
insert into city (name) values ('Nyírtét')
insert into city (name) values ('Beszterec')
insert into city (name) values ('Tardona')
insert into city (name) values ('Várvölgy')
insert into city (name) values ('Galgagyörk')
insert into city (name) values ('Bükkösd')
insert into city (name) values ('Sajóecseg')
insert into city (name) values ('Tolnanémedi')
insert into city (name) values ('Nagylók')
insert into city (name) values ('Nőtincs')
insert into city (name) values ('Penészlek')
insert into city (name) values ('Petőháza')
insert into city (name) values ('Tiszaderzs')
insert into city (name) values ('Kajászó')
insert into city (name) values ('Kölked')
insert into city (name) values ('Olaszfalu')
insert into city (name) values ('Sarród')
insert into city (name) values ('Kisvarsány')
insert into city (name) values ('Dormánd')
insert into city (name) values ('Nagylózs')
insert into city (name) values ('Hejőkeresztúr')
insert into city (name) values ('Kamut')
insert into city (name) values ('Bárna')
insert into city (name) values ('Ságújfalu')
insert into city (name) values ('Rábapordány')
insert into city (name) values ('Tiborszállás')
insert into city (name) values ('Rábahidvég')
insert into city (name) values ('Bogád')
insert into city (name) values ('Mihályi')
insert into city (name) values ('Hahót')
insert into city (name) values ('Gyulaj')
insert into city (name) values ('Balatonederics')
insert into city (name) values ('Himesháza')
insert into city (name) values ('Cserépfalu')
insert into city (name) values ('Tiszasas')
insert into city (name) values ('Kisnána')
insert into city (name) values ('Egervár')
insert into city (name) values ('Körösszegapáti')
insert into city (name) values ('Magyarnándor')
insert into city (name) values ('Pázmándfalu')
insert into city (name) values ('Bakonynána')
insert into city (name) values ('Aparhant')
insert into city (name) values ('Csősz')
insert into city (name) values ('Szászberek')
insert into city (name) values ('Zalaszentiván')
insert into city (name) values ('Somogyudvarhely')
insert into city (name) values ('Gyékényes')
insert into city (name) values ('Pusztamérges')
insert into city (name) values ('Berekfürdő')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Jordan', 'Norton', 'Ap #210-1059 Aliquet. St.', '691', '(656) 589-4641', 'nunc.nulla.vulputate@aol.ca')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Grady', 'Flores', '"Ap #193-4173 Montes', '1241', '(927) 852-0271', 'feugiat.metus@protonmail.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Cole', 'Meadows', '"P.O. Box 188', '9', '(354) 257-3781', 'sed.et.libero@aol.ca')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Shay', 'Dotson', '"5644 A', '471', '1-842-711-1937', 'vel.nisl@aol.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Drew', 'Norman', 'Ap #299-7164 Fringilla St.', '180', '1-443-740-5838', 'arcu.nunc@google.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Brenna', 'Ward', '"P.O. Box 947', '960', '1-451-604-5652', 'ornare.egestas@aol.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Colton', 'Mccarty', '483-8528 Semper Avenue', '398', '1-545-756-0258', 'felis@google.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Giselle', 'Blankenship', 'Ap #140-2409 Nec Rd.', '486', '1-578-671-0586', 'aliquam.auctor.velit@outlook.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Kenneth', 'Leon', '113-1074 Dolor Av.', '307', '(721) 636-2832', 'vel.venenatis.vel@icloud.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Aladdin', 'Lara', '589-7573 Pellentesque Rd.', '1238', '(185) 246-5884', 'eget.ipsum.donec@protonmail.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Wade', 'Herrera', '"298-5518 Lorem', '285', '1-498-335-1573', 'cum.sociis@hotmail.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Amery', 'Hardy', '"157-130 Elit', '635', '1-931-608-3255', 'nisl.elementum.purus@aol.ca')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Marshall', 'Welch', 'Ap #170-4274 Nec Road', '267', '(876) 454-7921', 'nec.enim@google.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Vaughan', 'Hull', 'Ap #294-5200 Ligula. Av.', '516', '1-155-678-8359', 'ac.ipsum@icloud.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Louis', 'Booth', '886-3539 Sed Road', '630', '(671) 446-7167', 'sem.magna.nec@hotmail.ca')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Barry', 'Huff', '"P.O. Box 528', '1230', '(725) 472-8257', 'ac.orci.ut@hotmail.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Elmo', 'Hall', '175-9776 Egestas Ave', '1239', '1-776-637-2344', 'et.malesuada@aol.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Freya', 'Lang', '572-1020 Lorem St.', '780', '(531) 661-4228', 'at.velit@outlook.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Noel', 'Harper', '"P.O. Box 526', '984', '1-522-877-7456', 'convallis.dolor@outlook.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Harlan', 'Ross', '"P.O. Box 744', '1304', '1-110-331-1236', 'volutpat.ornare@hotmail.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Curran', 'Robles', 'Ap #830-8552 Sapien. Street', '461', '1-871-182-0875', 'integer.mollis@hotmail.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Remedios', 'Hayden', 'Ap #678-6035 Vel Ave', '326', '(856) 851-3400', 'tristique@google.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Aladdin', 'Giles', 'Ap #902-7288 Nibh St.', '926', '1-234-684-1332', 'tellus.nunc.lectus@protonmail.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Bevis', 'Watkins', '678-5914 Orci. Street', '963', '1-725-118-2050', 'convallis.in.cursus@google.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Amir', 'Jensen', '141-8862 Curabitur Av.', '1130', '(309) 856-7492', 'integer.eu@icloud.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Lynn', 'David', '"Ap #658-7944 Non', '801', '(925) 227-8652', 'ante.maecenas@icloud.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Frances', 'Dalton', 'Ap #181-3815 Orci Avenue', '522', '1-221-616-4166', 'maecenas.ornare@protonmail.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Elliott', 'Fisher', '914-9032 Laoreet St.', '584', '1-612-314-1367', 'gravida.molestie.arcu@yahoo.ca')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Lacota', 'Salazar', 'Ap #929-6881 Faucibus Ave', '850', '(311) 387-9722', 'ut@icloud.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Felicia', 'Boyle', '831 Aliquet. Ave', '668', '1-672-527-2658', 'et@google.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Thane', 'Harmon', '477-7724 Leo. Road', '781', '1-634-914-2502', 'nisl.maecenas@outlook.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Lawrence', 'Sanford', '"P.O. Box 446', '727', '1-633-909-8597', 'dolor.nonummy@icloud.couk')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Hamish', 'Lowery', 'Ap #497-8374 Sagittis Rd.', '540', '(280) 951-1856', 'lectus.convallis@hotmail.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Rhea', 'Mclaughlin', '"Ap #463-8232 Congue', '407', '(653) 521-6517', 'non.justo@google.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Alice', 'Morin', 'Ap #408-8530 Suspendisse Rd.', '855', '(337) 550-1955', 'orci.adipiscing.non@protonmail.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Kelly', 'Larson', '883-8094 Nec Av.', '676', '(658) 494-5828', 'ac@protonmail.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Tate', 'Morrison', 'Ap #207-1216 Arcu St.', '824', '(433) 215-2315', 'lorem@google.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Benedict', 'Cotton', '285-3171 Nam Rd.', '1288', '(245) 663-6723', 'nunc.ullamcorper@protonmail.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Byron', 'Rojas', '826-8348 Mattis. St.', '610', '(493) 477-8738', 'elit.pretium@outlook.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Alvin', 'King', '6260 Quisque St.', '1233', '1-208-511-6165', 'maecenas.iaculis@hotmail.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Kaye', 'Heath', '811-9800 Etiam St.', '101', '(519) 503-6421', 'nulla.cras@yahoo.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Aladdin', 'Mayo', '"3105 Dolor', '89', '1-651-934-8433', 'convallis.in@protonmail.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Ayanna', 'Rasmussen', 'Ap #374-6470 Nisi. Av.', '261', '(488) 873-1312', 'nulla.semper.tellus@protonmail.org')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Carl', 'Mack', '"P.O. Box 404', '55', '(350) 484-0144', 'leo.morbi.neque@protonmail.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Thaddeus', 'Wilkinson', '761-2461 Sit Rd.', '414', '1-725-778-8773', 'quisque.nonummy@aol.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Karleigh', 'Cox', '"164-1794 Odio', '881', '(636) 861-0256', 'senectus.et.netus@aol.com')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Hashim', 'England', 'Ap #501-3423 Fusce St.', '913', '(439) 446-6164', 'at@aol.net')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Neve', 'Cervantes', 'Ap #116-7783 Dolor Rd.', '711', '(332) 312-5882', 'massa.non@yahoo.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Amaya', 'Valentine', '5443 Arcu. Street', '65', '1-478-827-6015', 'sed.molestie@aol.edu')
insert into customers (firstname, lastname, address, city_id, phone, email) values
('Petra', 'Hancock', '394-9682 Sollicitudin St.', '225', '(789) 388-4994', 'vitae.odio@aol.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Colorado', 'Larsen', '171-6915 Libero Avenue', '599', '1-643-234-0354', 'interdum.libero@outlook.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Malik', 'York', '720-3022 Amet Avenue', '1244', '(222) 247-3551', 'dictum.phasellus.in@icloud.ca')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Alvin', 'Mullins', '"P.O. Box 328', '1151', '(244) 776-6741', 'fusce@icloud.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Ciara', 'Harrison', '"P.O. Box 985', '127', '(533) 211-8681', 'amet.massa@protonmail.couk')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Fuller', 'Melendez', '1339 Porttitor Rd.', '819', '(359) 285-1625', 'vel@hotmail.net')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Wallace', 'Michael', 'Ap #742-7825 Venenatis Avenue', '275', '1-937-630-5523', 'ac@yahoo.couk')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Sydnee', 'Richardson', '"Ap #772-3791 Risus', '347', '(210) 895-2502', 'posuere.at@hotmail.couk')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Myles', 'Robinson', '770-6544 Donec Av.', '401', '1-781-240-9385', 'nullam.feugiat@yahoo.net')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Nell', 'Fields', 'Ap #373-5843 Tincidunt Avenue', '404', '1-855-662-7153', 'parturient.montes@hotmail.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Sonia', 'Morton', '375-4161 Et Rd.', '843', '1-994-353-8488', 'rutrum.non@aol.couk')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Maisie', 'Burt', '557-8290 Integer Ave', '408', '(438) 835-7886', 'tristique.senectus@google.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Kasper', 'Dalton', '"669-5426 Et', '463', '(369) 644-1779', 'non.lorem.vitae@aol.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Quyn', 'Cantu', '6814 Donec Ave', '642', '(832) 604-4080', 'diam.eu@aol.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Marvin', 'Bonner', 'Ap #544-7596 Ligula. Av.', '1272', '(662) 854-7463', 'pharetra@aol.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Geraldine', 'Glenn', '"P.O. Box 155', '787', '(848) 582-0832', 'imperdiet.nec@icloud.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Kareem', 'Terrell', 'Ap #482-1989 Mus. Av.', '477', '(722) 371-4553', 'duis.sit@aol.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Sydney', 'Evans', '313-6932 Ut Avenue', '83', '(402) 743-3911', 'laoreet.libero.et@google.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Cole', 'Wooten', 'Ap #419-4087 Velit St.', '221', '(683) 491-3707', 'nec@outlook.couk')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Connor', 'Cantrell', 'Ap #653-1211 Donec Avenue', '1112', '(474) 720-0165', 'suspendisse@yahoo.ca')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Iola', 'Mathis', '574-8065 Aenean Rd.', '426', '(643) 568-5536', 'facilisis@aol.org')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Ariana', 'Hobbs', '"Ap #895-3927 Non', '80', '(431) 529-6893', 'vulputate.mauris@google.edu')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Tarik', 'Mckay', 'Ap #506-1079 Aliquet St.', '413', '(751) 628-6845', 'augue.ut@protonmail.org')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Patricia', 'Mays', 'Ap #799-1873 Vitae Ave', '1161', '(471) 745-5371', 'vulputate.posuere@icloud.org')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Keegan', 'Hartman', 'Ap #190-4012 Lectus. Rd.', '1192', '1-837-387-9171', 'molestie.arcu.sed@yahoo.com')
insert into employee (firstname, lastname, address, city_id, phone, email) values
('Deacon', 'Lester', '102-5000 Consectetuer Street', '595', '(261) 891-9681', 'elit.sed.consequat@aol.net')
